In [ ]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    return (f(x + delta_x) - f(x-delta_x)) / (2*delta_x)


In [1]:
def my_func1(x):
    return x**2

def numerical_derivative(f, x):
    delta_x = 1e-4
    return (f(x + delta_x) - f(x-delta_x)) / (2*delta_x)

result = numerical_derivative(my_func1, 3)

print("result = ", result)

result =  6.000000000012662


In [3]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

result1 = numerical_derivative(my_func2, 2)
print("result1 = ", result1)

result1 =  66.50150507518049


In [15]:
# 수치미분 최정 버전 

import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val  = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    return grad
        
        

In [16]:
def func1(input_obj):
    x = input_obj[0]
    return x**2

numerical_derivative(func1, np.array([5.0]))

array([10.])

In [17]:
def func2(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    
    return (2*x + 3*x*y + np.power(y,3))
input = np.array([1.0, 2.0])

numerical_derivative(func2, input)

array([ 8.        , 15.00000001])

## Linear Regression

In [14]:
import numpy as np

x_data = np.array([[2,3],[4,3],[6,4],[8,6],[10,7],[12,8],[14,9]])
t_data = np.array([0,0,0,1,1,1,1]).reshape(7,1)

W = np.random.rand(2,1)
b = np.random.rand(1)
print("W = ",W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

def loss_func(x, t):
    y = np.dot(x,W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

W =  [[0.97615349]
 [0.18406957]] , W.shape =  (2, 1) , b =  [0.0505293] , b.shape =  (1,)


In [15]:
# 손실 함수 정의

def loss_func(x, t):
    y = np.dot(x,W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

In [16]:
def error_val(x, t):
    y = np.dot(x,W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

def predict(x):
    y = np.dot(x,W) + b
    return y


In [18]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val  = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    return grad

In [19]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)
print("initial error value = ", error_val(x_data, t_data), "initial W = ", W, "\n", ", b = ", b)

for step in range(8001):
    W -= learning_rate *numerical_derivative(f, W)
    b -= learning_rate *numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ", b)

initial error value =  84.68101353144736 initial W =  [[0.97615349]
 [0.18406957]] 
 , b =  [0.0505293]
step =  0 error value =  148.68397534795167 W =  [[-0.66896128]
 [-0.94023378]] , b =  [0.27543638]
step =  400 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.65397633e+12]] , b =  [5.50716232e+10]
step =  800 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.65397633e+12]] , b =  [5.50716232e+10]
step =  1200 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.65397633e+12]] , b =  [5.50716232e+10]
step =  1600 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.65397633e+12]] , b =  [5.50716232e+10]
step =  2000 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.65397633e+12]] , b =  [5.50716232e+10]
step =  2400 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.65397633e+12]] , b =  [5.50716232e+10]
step =  2800 error value =  2.2659978817770826e+24 W =  [[ 1.23314497e+12]
 [-1.6539

In [22]:
test_data = np.array([7,6])
predict(test_data)

array([-1.23677152e+12])