# <center> <기계학습의 원리> 연습문제 </center>

### 아이리스는 꽃잎의 모양과 길이에 따라 여러가지 품종으로 나뉜다. iris.csv 파일에는 다음과 같이 150개의 아이리스 정보와 품종에 대한 데이터가 나열되어 있다.
|                | 정보1 | 정보2 | 정보3 | 정보4 | 품종           |
|--------	     |------ |------ |------ |------ |------          |
| 1번째 아이리스 | 5.1   | 3.5   | 4.0   | 0.2   | Iris-setosa    |
| 2번째 아이리스 | 4.9   | 3.0   | 1.4   | 0.2   | Iris-setosa    |
| 3번째 아이리스 | 4.7   | 3.2   | 1.3   | 0.3   | Iris-setosa    |
|  ...           | ...   | ...   | ...   | ...   | ...            |
|150번째 아이리스| 5.9   | 3.0   | 5.1   | 1.8   | Iris-virginica |

* 샘플 수: 150
* 속성 수: 4
 
  > 정보 1: 꽃받침 길이 (단위: cm)
  
  > 정보 2: 꽃받침 너비 (단위: cm)

  > 정보 3: 꽃잎 길이 (단위: cm)

  > 정보 4: 꽃잎 너비 (단위: cm)
* 클래스: Iris-setosa, Iris-versicolor, Iris-virginica

### (1) 이 데이터에서 150개의 샘플을 무작위로 섞은 후(Hint: tensorflow의 shuffle함수를 사용할 것) 임의로 100개의 샘플을 뽑아서 다중분류 알고리즘을 작성하고 이를 학습하여라. 
### (2) 나머지 50개의 데이터로 기 작성된 알고리즘의 정확도(accuracy)를 계산하여 출력하라. (이때 최대한 정확도를 높일수록 높은 점수가 부여된다. )

In [ ]:
  # https://jfun.tistory.com/43

In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
#loading the iris dataset
iris = load_iris()

In [3]:
#training data 설정
x_train = iris.data[:-30]
y_train = iris.target[:-30]

#test data 설정
x_test = iris.data[-30:] # test feature data
y_test = iris.target[-30:] # test feature data

In [4]:
print(y_train)
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [5]:
#RandomForestClassifier 클래스를 import
from sklearn.ensemble import RandomForestClassifier

In [6]:
#tree의 개수 Random Forest 분류 모듈 생성
rfc = RandomForestClassifier(n_estimators=10)
rfc

RandomForestClassifier(n_estimators=10)

In [7]:
# rfc.fin()에 훈련 데이터를 입력해 Random Forest 모듈을 학습
rfc.fit(x_train, y_train)
#Test data를 입력해 target data를 예측 (매번 달라짐)
prediction = rfc.predict(x_test)
#예측 결과 precision과 실제 test data의 target을 비교
print(prediction==y_test)

#Random forest 정확도 측정
rfc.score(x_test, y_test)

[ True False  True False  True  True False False  True  True  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True False]


0.7333333333333333

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [9]:
print("Accuracy is: ", accuracy_score(prediction, y_test))
print(classification_report(prediction, y_test))

Accuracy is:  0.7333333333333333
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         8
           2       0.73      1.00      0.85        22

    accuracy                           0.73        30
   macro avg       0.37      0.50      0.42        30
weighted avg       0.54      0.73      0.62        30



C:\Users\USER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
from sklearn.model_selection import train_test_split

x = iris.data
y = iris.target


X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)


In [11]:
print(y_test)
print(Y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[2 0 2 0 1 2 2 1 2 0 0 2 2 2 1 2 0 1 1 1 1 0 2 2 0 0 0 2 1 1]


In [12]:
clf = RandomForestClassifier(n_estimators=10)
clf.fit(X_train, Y_train) # X_train과 Y_train을 입력해 모듈을 학습 시킨다.
prediction_1 = rfc.predict(X_test)

#print(prediction_1 == Y_test)
print("Accuracy is: ", accuracy_score(prediction_1, Y_test))

print(classification_report(prediction_1, Y_test))

Accuracy is:  0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.82      0.90        11
           2       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



In [13]:
# Initialize the model
clf_2 = RandomForestClassifier(n_estimators=200,     # Number of trees
                              max_features=4,     # Num features considered
                              oob_score=True)     # Use OOB scoring


In [14]:
clf.fit(X_train, Y_train)
prediction_2 = clf.predict(X_test)
print(prediction_2 == Y_test)
print("Accuracy is : ", accuracy_score(prediction_2, Y_test))
print("======================================================")
print(classification_report(prediction_2, Y_test))

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True  True  True  True  True
  True  True  True False  True  True]
Accuracy is :  0.9
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.75      0.86        12
           2       0.75      1.00      0.86         9

    accuracy                           0.90        30
   macro avg       0.92      0.92      0.90        30
weighted avg       0.93      0.90      0.90        30

